version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 4000
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVER_HEAP: 128  # Минимум памяти
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok"
    ports:
      - "2181:2181"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc 127.0.0.1 2181 | grep imok || exit 0"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 120s

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
      KAFKA_JVM_PERFORMANCE_OPTS: "-XX:MaxInlineLevel=15 -XX:MaxTrivialSize=12"
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: es-node
    environment:
      - node.name=es-node
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_TMPDIR=/tmp"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./es-config/certs:/usr/share/elasticsearch/config/certs
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 10

  # Остальные сервисы с уменьшенными требованиями...

networks:
  elastic:
    driver: bridge

volumes:
  es-data:
    driver: local